### ISSUE TITLE
EPIC: Chat UI

### ISSUE THREAD

**Issue by gphorvath** [defenseunicorns/leapfrogai#183]
Problem Statement:
In order to interact with the LLM we require a User Interface. Few open source projects exist that are actively supported.

Acceptance Criteria:
- [ ] A UI exists that allows the user to perform chat with an OpenAI streaming endpoint
- [ ] The UI exposes configuration parameters such as temperature, system prompt, model backend, and more.

Definition of Done
- [ ] A major version of LeapfrogAI ChatUI containing the above stated features has been released.

POCs:
@gerred
@YrrepNoj

**Comment by CollectiveUnicorn** [comment]
Current repo where this work is being done: https://github.com/defenseunicorns/ask-frogs-dash-days - will continue here until the application has been cleaned up. Then move it over to another repo or rename the existing repo (this preferably).
