### ISSUE TITLE
ADR: Out-of-the-Box RAG Solutions

### ISSUE THREAD

**Issue by barronstone** [defenseunicorns/leapfrogai#318]
**Description:**
The backend API requires a database for data persistence. An architectural decision needs to be made regarding which database technology to use, considering factors such as scalability, performance, data model, and team expertise.

**Tasks:**
- [ ] Identify potential OSS solutions for RAG that could be used in place of our home-built solution
- [ ] Evaluate potential solutions to compare the pros/cons with a home-built solution
- [ ] Write ADR explaining decision and rationale
- [ ] If appropriate, create new issues/EPIC in backlog for the proposed course of action
