### ISSUE TITLE
ADR: RAG Multitenancy Approach

### ISSUE THREAD

**Issue by barronstone** [defenseunicorns/leapfrogai#319]
**Description:**
To deliver RAG (e.g. "chat with your docs") capabilities in a SaaS-type environment, we need to determine our approach to multitenancy. How can we ensure a clear separation of mission data between organizations, as well as ensure individual users can only access data for which they have permissions/privilege (e.g., ABAC/RBAC)? 

**Tasks:**
- [ ] Identify the challenges with and approaches for hosting a multi-tenant environment with RAG on mission data
- [ ] Understand how that fits into the approach for a SaaS offering on UDS.us
- [ ] Understand how that fits into the approach for deployments into mission hero environments (e.g., AWS GovCoud, On-Pem, etc.)
- [ ] Document proposed path to achieve separation of data to support multitenancy
- [ ] Capture decision in an ADR and gain LFAI team approval
- [ ] Create relevant issues in the backlog for the proposed approach

**Comment by gregclark-defenseunicorns** [comment]
@barronstone Does this need to stay open?
