### ISSUE TITLE
user(test) - parent

### ISSUE THREAD

**Issue by gregclark-defenseunicorns** [defenseunicorns/leapfrogai#692]
```[tasklist]
### Linked Issues
- [ ] https://github.com/defenseunicorns/leapfrogai/issues/693
- [ ] https://github.com/defenseunicorns/leapfrogai/issues/694
- [ ] https://github.com/defenseunicorns/leapfrogai/issues/695
```
