### ISSUE TITLE
EPIC: Evaluations MVP

### ISSUE THREAD

**Issue by jalling97** [defenseunicorns/leapfrogai#723]
# Evaluations MVP

## Description
LFAI needs a framework for evaluations in order to:
- Validate the efficacy of RAG at all stages
- Make model recommendations for various scenarios
- Establish a baseline for future improvements
- Sanity check that base model functionality is implemented properly

The MVP for this evaluations framework will be limited in scope to the following evaluation scenarios:
- **Chat** - regular chat-based interactions with the llm without added context
- **Chat with your docs** - RAG-enabled chat interactions that require retrieved context

This framework can be expanded upon as LFAI develops, but this epic covers an MVP that accomplishes the above goals.

## Completion Criteria
- [x] Decision of what toolset should be used to handle evaluations ([Deepeval](https://docs.confident-ai.com/))
    - https://github.com/defenseunicorns/leapfrogai/issues/196
- [ ] Identification of 1 or more existing evaluation datasets for rapid prototyping
    - https://github.com/defenseunicorns/leapfrogai/issues/715
- [ ] Creation of a custom dataset that is mission-focused while remaining openly available for more targeted evaluations
    - https://github.com/defenseunicorns/leapfrogai/issues/716
- [ ] Determine a list of open-source models to evaluate on
    - https://github.com/defenseunicorns/leapfrogai/issues/717
- [ ] Establishment of which [evaluation metrics](https://docs.confident-ai.com/docs/metrics-introduction) and custom heuristics should be used
    - https://github.com/defenseunicorns/leapfrogai/issues/718
- [ ] Decision of what evaluator llm should be used for [llm-as-a-judge](https://docs.arize.com/phoenix/evaluation/concepts-evals/llm-as-a-judge) evaluations
   - https://github.com/defenseunicorns/leapfrogai/issues/719
- [ ] Decision on how evals will be run (workflow? ad-hoc python script? notebook?)
    - https://github.com/defenseunicorns/leapfrogai/issues/720
- [ ] Determine what the "Unicorn model card" should look like (i.e how the evaluation results are delivered/conveyed)
    - https://github.com/defenseunicorns/leapfrogai/issues/721
