### ISSUE TITLE
EPIC: Made for UDS

### ISSUE THREAD

**Issue by justinthelaw** [defenseunicorns/leapfrogai#727]
**Description:**

`Made for UDS` ([as described here](https://github.com/defenseunicorns/uds-common/blob/main/docs/uds-package-practices.md)) is a badge and set of acceptance criteria that are used to determine if an (set of) application(s) or service(s) are supported by the UDS runtime and approved by the UDS team.

**Acceptance Criteria:**

The following `MUST` tasks need to be completed in order for the `Made for UDS` badge to be applied to the LeapfrogAI repository.

`MUST` tasks:
- [ ] https://github.com/defenseunicorns/leapfrogai/issues/297
- [ ] https://github.com/defenseunicorns/leapfrogai/issues/696
- [ ] https://github.com/defenseunicorns/leapfrogai/issues/702
- [ ] https://github.com/defenseunicorns/leapfrogai/issues/703
- [ ] https://github.com/defenseunicorns/leapfrogai/issues/638 (UI tests back into E2E workflow)
- [ ] https://github.com/defenseunicorns/leapfrogai/issues/707
- [ ] https://github.com/defenseunicorns/leapfrogai/issues/704 (is a `SHOULD`, but we need this)

**Additional Context:**

The following are `SHOULD` tasks that do not need to be completed to close this EPIC, but should be tracked as future technical debt issues:

`SHOULD` tasks:
- [ ] https://github.com/defenseunicorns/leapfrogai/issues/701
- [ ] https://github.com/defenseunicorns/leapfrogai/issues/705
- [ ] https://github.com/defenseunicorns/leapfrogai/issues/706
- [ ] https://github.com/defenseunicorns/leapfrogai/issues/708
- [ ] https://github.com/defenseunicorns/leapfrogai/issues/711
- [ ] https://github.com/defenseunicorns/leapfrogai/issues/709
