### ISSUE TITLE
EPIC: IronBank LeapfrogAI Hardening

### ISSUE THREAD

**Issue by justinthelaw** [defenseunicorns/leapfrogai#750]
## Description

Creating hardened [IronBank](https://docs-ironbank.dso.mil/overview/) "flavors" for different images that make up the LeapfrogAI stack provides the following benefits for all LeapfrogAI end-users:

1. Obtain a Certificate to Field (CtF) for deployment of LeapfrogAI to [PlatformONE's PaaS](https://p1.dso.mil/)
2. Gain reciprocity for other deployment platforms that accept the PlatformONE ATO
3. Enable "easier" ATO on other programs that accept IronBank images as drop-in replacements
4. Provide another open-source, hardened image option beyond [Chainguard](https://www.chainguard.dev/) and upstream vendor containers

## Acceptance Criteria

The following issues or tasks must be closed or completed in order to complete this EPIC:

```[tasklist]
### Tasks:
- [ ] https://github.com/defenseunicorns/leapfrogai/issues/730
- [ ] https://github.com/defenseunicorns/leapfrogai/issues/736
- [ ] https://github.com/defenseunicorns/leapfrogai/issues/731 [^1]
- [ ] https://github.com/defenseunicorns/leapfrogai/issues/735 [^1]
- [ ] https://github.com/defenseunicorns/leapfrogai/issues/737 [^1]
```

- [ ] https://github.com/defenseunicorns/leapfrogai/issues/730
- [ ] https://github.com/defenseunicorns/leapfrogai/issues/736
- [ ] https://github.com/defenseunicorns/leapfrogai/issues/731 [^1]
- [ ] https://github.com/defenseunicorns/leapfrogai/issues/735 [^1]
- [ ] https://github.com/defenseunicorns/leapfrogai/issues/737 [^1]

[^1]: May require the creation of a `feat:` issue after spike findings are reported

### Potential Blockers

The following is a running list of potential blockers, in the form of EPICs and/or issues, that could slowdown and/or disrupt the progress of this EPIC:

- https://github.com/defenseunicorns/leapfrogai/issues/460
- https://github.com/defenseunicorns/leapfrogai/issues/703
- https://github.com/defenseunicorns/leapfrogai/issues/623

### Dependent Issues

The following is a running list of other EPICs and/or issues that are dependent on the closure of this EPIC:

- https://github.com/defenseunicorns/leapfrogai/issues/727
    - https://github.com/defenseunicorns/leapfrogai/issues/704
    - https://github.com/defenseunicorns/leapfrogai/issues/707
- https://github.com/defenseunicorns/leapfrogai/issues/367

### LeapfrogAI Images

The base image(s) include the "upstream" variant we use today, and the "possible IronBank" drop-in we could use for container re-base testing, if it exists.

1. LeapfrogAI API
    - Python 3.11 ([upstream](https://github.com/defenseunicorns/leapfrogai-images/pkgs/container/leapfrogai%2Fpython)) ([possible IronBank](https://registry1.dso.mil/harbor/projects/3/repositories/opensource%2Fpython/artifacts-tab/artifacts/sha256:c4e87e2cd07e20d4b9ff9b67479648060d773d986eda5c353d0071cf679b27db))
2. (Bitnami) Supabase Operator[^2]
    - GoTrue ([upstream](https://hub.docker.com/layers/bitnami/gotrue/2.149.0-debian-12-r0/images/sha256-23e1b7f6a52cf9132c40729c751322f1ff3e47efecac81f94c7489c2d1bec619?context=explore))
    - JWT-CLI ([upstream](https://hub.docker.com/layers/bitnami/jwt-cli/6.0.0-debian-12-r19/images/sha256-e7dded93a638c548878d4628c5a8f07b7971cb224ef6bd29d12307c51bbd96ec?context=explore))
    - Kubectl ([upstream](https://hub.docker.com/layers/bitnami/kubectl/1.29.3-debian-12-r4/images/sha256-6d604587a25b8f5e4bf1c5ddebcef06a857cc02631b680b7be9e0684f7e97d76?context=explore))
    - OS-shell ([upstream](https://hub.docker.com/layers/bitnami/os-shell/12-debian-12-r18/images/sha256-1d9537a014c5f7e2b912c96ad96fcc56cdc8b37c8119ca3b9bd604c6002aa6e3?context=explore))
    - Postgrest ([upstream](https://hub.docker.com/layers/bitnami/postgrest/11.2.2-debian-12-r14/images/sha256-f80e0bbb718a4538f7cdc017f1e7882c73b972bb6f74efe30ffe0c43c4942edf?context=explore))
    - Kong ([upstream](https://hub.docker.com/layers/bitnami/kong/3.6.1-debian-12-r13/images/sha256-e6f095b9b48f3626d0c45d50b473a8e8ec8f615a92abfe83db4e0dd86bc78d63?context=explore))
    - Supabase-Postgres ([upstream](https://hub.docker.com/layers/bitnami/supabase-postgres/15.1.1-debian-12-r24/images/sha256-d06c1347ee8e5b8aa746e832d4875e93a6e9ff79a75a8f7bf9045d880c4d7b0c?context=explore))
    - Supabase-Postgres-Meta ([upstream](https://hub.docker.com/layers/bitnami/supabase-postgres-meta/0.80.0-debian-12-r1/images/sha256-d4edf7205774e0280dfb0ec79b355e3f3896fbfeb461dac1f8f060b57117e5d8?context=explore))
    - Supabase-Realtime ([upstream](https://hub.docker.com/layers/bitnami/supabase-realtime/2.28.22-debian-12-r0/images/sha256-3a7936665a7a6b508d6e994ed94300cf49fb6432bd399aa585e35ff7a0bf8e9b?context=explore))
    - Supabase-Storage ([upstream](https://hub.docker.com/layers/bitnami/supabase-storage/0.48.4-debian-12-r0/images/sha256-4b3ed924972840f4dcdce3d22b19af1ad0905a9693efac2f9f0f205532cffb10?context=explore))
    - Supabase-Studio ([upstream](https://hub.docker.com/layers/bitnami/supabase-studio/0.24.3-debian-12-r0/images/sha256-93f34bb9cf25e434be6b46e3a29bf0c445cfd5aae2a262b544f52966932dfa28?context=explore))

3. Migrations ([upstream](https://hub.docker.com/r/chainguard/bash/)) ([possible IronBank](https://registry1.dso.mil/harbor/projects/3/repositories/redhat%2Fubi%2Fubi9/artifacts-tab/artifacts/sha256:fea95ca309bc8dc8bb4a5059f890e066bf0772d7b38287239539cf3822f63071))
4. LeapfrogAI UI
    - Node 18 ([upstream](https://hub.docker.com/layers/library/node/18-alpine/images/sha256-538e4e1286473c79ec415222d2ed61c1112c00056ad7f212ce64c15c908bde41?context=explore)) ([possible IronBank](https://registry1.dso.mil/harbor/projects/3/repositories/opensource%2Fnodejs%2Fnodejs18/artifacts-tab/artifacts/sha256:1e5d5778b5baf26d7c83b50d5ea029d1378c25528d0806f1356e5682012ecdb2))
    - Chainguard Node-Latest ([upstream](https://hub.docker.com/r/chainguard/node/)) ([possible IronBank](https://registry1.dso.mil/harbor/projects/3/repositories/chainguard-dev%2Fwolfi%2Fnode/artifacts-tab/artifacts/sha256:aa922ba4ec126fc314365613945570c851eefb4f56162cfc86eca73f238b024c))

5. vLLM backend ([upstream](https://hub.docker.com/layers/nvidia/cuda/12.2.2-devel-ubuntu22.04/images/sha256-a64a5a4a0638034aef2194276b8306e161a5a020dee5a13849ff5320c9ac0992?context=explore)) ([possible IronBank](https://registry1.dso.mil/harbor/projects)) ([possible IronBank, but needs updating](https://repo1.dso.mil/dsop/nvidia/cuda/devel-w-python))
6. LLaMA-CPP-Python backend  ([upstream](https://github.com/defenseunicorns/leapfrogai-images/pkgs/container/leapfrogai%2Fpython)) ([possible IronBank](https://registry1.dso.mil/harbor/projects))
7. Text-Embeddings backend ([upstream](https://github.com/defenseunicorns/leapfrogai-images/pkgs/container/leapfrogai%2Fpython)) ([possible IronBank](https://registry1.dso.mil/harbor/projects))
8. Whisper ([upstream](https://github.com/defenseunicorns/leapfrogai-images/pkgs/container/leapfrogai%2Fpython)) ([possible IronBank](https://registry1.dso.mil/harbor/projects))

[^2]: Bitnami's Supabase Helm deployment is highly-coupled and there is a lack of the specific Bitnami-flavor images on the [IronBank/Bitnami sub-project](https://repo1.dso.mil/dsop/bitnami). Please see the spike required to confirm which IronBank images can be drop-in replacements for these Bitnami-flavor images.

### Resources and Links

- [RepoONE](https://repo1.dso.mil/)
- [Defense Unicorns RepoONE Sub-Project](https://repo1.dso.mil/dsop/opensource/defenseunicorns)
- [IronBank Harbor Registry](https://registry1.dso.mil/harbor/projects)
- [IronBank Registry](https://ironbank.dso.mil/about)
- [PlatformONE IL2 Slack](https://chat.il2.dso.mil/)
- [Shadow's Edge Ollama IronBank repository](https://repo1.dso.mil/dsop/shadowsedge/shadowllama/ollama/)
- [Pepr P1 Developer Documentation](https://docs.google.com/document/d/1f_LVs0bui_rDhKzbnJjCSmI3Z9hkGDbVkt_1WWV6vdA/edit#heading=h.z5nzzoqrllus)
- [Iron Bank Onboarding](https://docs-ironbank.dso.mil/overview/)
- [IronBank Hardening Guide](https://docs-ironbank.dso.mil/hardening/overview/)
- [IronBank Contributing Guide](https://docs-ironbank.dso.mil/quickstart/contributor-onboarding/)
- [IronBank Fetch Resources Tool](https://docs-ironbank.dso.mil/tutorials/local/)

### Additional POCs

**Defense Unicorns Product:** @mjnagel @cmwylie19 

**Defense Unicorns Delivery:** @gscallon @vanakema @CodyDamewood @phillip-record @americanthinker

**Comment by justinthelaw** [comment]
Submitted onboarding document/questionnaire with request for the creation of all repos as outlined in the EPIC description above, with repo pattern `opensource/defenseunicorns/leapfrogai/<optional sub-directory>/<container name>`

**Comment by justinthelaw** [comment]
We have created a new [Repo1 LeapfrogAI Project](https://repo1.dso.mil/dsop/opensource/defenseunicorns/leapfrogai).

Below is a recommended (DRAFT) RACI for the development and maintenance of each hardened container: 

| IronBank Container | Responsible[^1] | Accountable[^2]     | Consulted[^3]                | Informed[^4]                                                |
| ------------------ | --------------- | ------------------- | ---------------------------- | ----------------------------------------------------------- |
| api                | @barronstone    | @justinthelaw + TBD | @YrrepNoj                    | @defenseunicorns/mission-ops-team @defenseunicorns/delivery |
| ui                 | @barronstone    | TBD                 | @YrrepNoj @andrewrisse       | @defenseunicorns/mission-ops-team @defenseunicorns/delivery |
| supabase[^5]       | @barronstone    | TBD                 | @YrrepNoj @CollectiveUnicorn | @defenseunicorns/mission-ops-team @defenseunicorns/delivery |
| migrations[^6]     | @barronstone    | TBD                 | @YrrepNoj                    | @defenseunicorns/mission-ops-team @defenseunicorns/delivery |
| vllm               | @barronstone    | @justinthelaw + TBD | @YrrepNoj                    | @defenseunicorns/mission-ops-team @defenseunicorns/delivery |
| llama-cpp-python   | @barronstone    | @justinthelaw + TBD | @YrrepNoj                    | @defenseunicorns/mission-ops-team @defenseunicorns/delivery |
| whisper            | @barronstone    | @justinthelaw + TBD | @YrrepNoj                    | @defenseunicorns/mission-ops-team @defenseunicorns/delivery |
| text-embeddings    | @barronstone    | @justinthelaw + TBD | @YrrepNoj                    | @defenseunicorns/mission-ops-team @defenseunicorns/delivery |

[^1]: The person or team who does the work. There should only be one responsible person or team per task. E.g., Justin Law + Gregory Horvath
[^2]: The person who owns the work and is responsible for its completion. They may not be the person doing the work, but they are ultimately responsible if it's not completed. E.g., Barron Stone
[^3]: The person or people who provide input or knowledge before the work can be done and signed off on. They may use their subject knowledge to suggest changes or improvements. E.g., Jonathan Perry
[^4]: The person or people who need to be kept up to date on the progress, process execution, and quality of the work. They may also need to be informed of challenges and setbacks. E.g., Mission Operations Value Stream
[^5]: Drop-in replacement spikes and development for the following containers and/or base images (11 total): GoTrue, JWT-CLI, Kubectl, OS-shell, Postgrest, Kong, Supabase-Postgres, Supabase-Postgres-Meta, Supabase-Realtime, Supabase-Storage, Supabase-Studio
[^6]: Drop-in replacement spikes and development for migration for the following containers and/or base images (3 total): Supabase, API, and UI

**Comment by gscallon** [comment]
Access update: @vanakema and I have received access to the Defense Unicorns and Leapfrog groups within Iron Bank and on the VAT

**Comment by andrewrisse** [comment]
blocked until presentation @justinthelaw

**Comment by justinthelaw** [comment]
Updates to this EPIC:

1. Due to Bitnami's end-of-life for Supabase Bitnami charts and containers, the Bitnami/Supabase task may change in scope depending on the results of [this issue](https://github.com/defenseunicorns/leapfrogai/issues/968)
2. The `registry1` flavored API is now [merged into the main](https://github.com/defenseunicorns/leapfrogai/pull/920) branch of LeapfrogAI, which includes the creation of `upstream` flavors by default
