### ISSUE TITLE
Modular Deployments

### ISSUE THREAD

**Issue by runyontr** [defenseunicorns/leapfrogai#91]
The zarf package for Leapfrog is too large and doesn't enable model zoos nicely.  Here's the proposed order of how to execute on splitting up Leapfrog to enable dynamic addition of models

```[tasklist]
### Tasks
- [ ] https://github.com/defenseunicorns/leapfrogai/issues/98
- [ ] https://github.com/defenseunicorns/leapfrogai/issues/95
- [ ] https://github.com/defenseunicorns/leapfrogai/issues/96
- [ ] https://github.com/defenseunicorns/leapfrogai/issues/97
```
